config/routes.rb
Rails.application.routes.draw do
  root to: 'top#main'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/users/new' => 'users#new'
  get '/users/:id' => 'users#show'
  delete '/users/:id', to: 'users#destroy'
  get '/recruitments/new', to: 'recruitments#new'
  get '/recruitments/search', to: 'recruitments#search'
  delete '/recruitments/:id', to: 'recruitments#destroy'
  post '/recruitments/index', to: 'recruitments#update'
  get '/recruitments/:id', to: 'recruitments#show'
  
  resources :users
  resources :recruitments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recruitment.rb
class Recruitment < ApplicationRecord
    
    belongs_to :user
    
    validates :rank,    length: { maximum: 15 }, presence: true
    validates :play_style,    length: { maximum: 15 }, presence: true
    
#   scope :search, -> (search_params) do
#       return if search_params.blank?
#        
#       rank(search_params[:rank])
#        mode(search_params[:mode])
#        want_chara_like(search_params[:want_chara])
#    end
    
#    scope :rank, -> (rank) { where('rank ?', "%#{rank}") if rank.present? }
end

app/models/user.rb
class User < ApplicationRecord
    
    validates :name, presence: true, length: { maximum: 20, allow_blank: true }, uniqueness: true
    validates :discord_id, presence: true, length: { maximum: 20, allow_blank: true }
    has_secure_password
    
    validates :password, presence: true, length: { minimum: 6 }
#    validates :name, presence: true, uniqueness: true
#    validates :discord_id, presence: true, uniqueness: true
#    validates :password_confirmation, presence: true
    
    has_many :recruitments, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    before_action :login_required
    
    
    
    add_flash_types :success, :info, :warning, :danger
    
    
    
    private
    
    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end
    
    def login_required
       redirect_to root_url unless current_user
    end
end

app/controllers/recruitments_controller.rb
class RecruitmentsController < ApplicationController
  before_action :login_required
  
  def index
    @user = User.find_by(id: session[:user_id])
    @recruitments = Recruitment.all.order(id: "DESC").page(params[:page]).without_count.per(10)
  end

  def new
    @recruitment = Recruitment.new
  end
  
  def create
    @recruitment = current_user.recruitments.new(recruitment_params)
    if @recruitment.use_chara == @recruitment.need_chara
      redirect_to recruitments_new_path, warning: "使うキャラと使って欲しいキャラは同一のキャラを選べません"
    elsif @recruitment.save
      redirect_to recruitments_path, success: "投稿しました"
    else
      render 'new'
    end
  end
  
  def update
    @recruitment = Recruitment.find(params[:id])
    @recruitment.update(recruitment_params)
    redirect_to recruitments_path
  end
  
  def show
    @recruitment = Recruitment.find(params[:id])
  end
  
  def destroy
    @recruitment = Recruitment.find(params[:id])
    if @recruitment.user_id == session[:user_id]
      @recruitment.destroy
      redirect_to recruitments_path
    end
  end
  
  def search
    
    if params[:mode]=="指定無し" && params[:want_chara]=="誰でも"
      @recruitments = Recruitment.where(flag: 0).order(id: "DESC")
    elsif params[:mode]=="指定無し"
      @recruitments = Recruitment.where(need_chara: "誰でも", flag: 0).or(Recruitment.where(need_chara: params[:want_chara])).order(id: "DESC")
    elsif params[:want_chara] == "誰でも"
      @recruitments = Recruitment.where(mode: params[:mode], flag: 0).order(id: "DESC")
    else
      @recruitments = Recruitment.where(mode: params[:mode], need_chara: params[:want_chara], flag: 0).order(id: "DESC")
    end
    
    if @recruitments.count==0
      redirect_to recruitments_path, warning: "検索結果にマッチするものがありませんでした"
    end
    
  end
  
  def edit
  end
  
  private
  
  def recruitment_params
    params.require(:recruitment).permit(:mode, :rank, :use_chara, :need_chara, :play_style, :flag)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  skip_before_action :login_required
  
  def new
  end
  
  def create
    user = User.find_by(name: session_params[:name])
    
    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to recruitments_path, info: "ログインしました"
    else
      redirect_to login_url, danger: "ログインに失敗しました"
    end
  end
  
  def destroy
    reset_session
    redirect_to root_url, warning: "ログアウトしました"
  end
  
  private
  
  def session_params
    params.require(:session).permit(:name, :password)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  skip_before_action :login_required
  def main
    if session[:user_id].nil?
      @recruitments = Recruitment.all.order(id: "DESC")
    else
      redirect_to recruitments_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      redirect_to login_url, success: "登録完了　ログインしてください"
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @recruitments = Recruitment.where(user_id: @user.id).order(id: "DESC")
    if @recruitments.count > 9
      _recs_most_mode = @recruitments.pluck(:mode)
      @most_mode = _recs_most_mode.group_by{|e| e}.max_by{|_,v| v.size}.first
      _recs_most_chara = @recruitments.pluck(:use_chara)
      @most_chara = _recs_most_chara.group_by{|e| e}.max_by{|_,v| v.size}.first
    else
      @most_mode = "データ数を増やしたら良く遊ぶモードが分かるよ"
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    if @user.id == session[:user_id]
      @user.destroy
      reset_session
      redirect_to root_path
    end
  end
  
  
  private
  
  def user_params
    params.require(:user).permit(:name, :discord_id, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recruitments_helper.rb
module RecruitmentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if @recruitment.errors.any? %>
  <div class="alert alert-warning">
    <ul>
        <% @recruitment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Find Apex Friends</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
    Find Apex Friends
  </header>
  <% flash.each do |key, value| %>
   <p class="alert alert-<%= key %>">
     <%= value %>
   </p>
<% end %>
  <body>
    <%= yield %>
  </body>
  <footer>
    
  </footer>
</html>

app/views/recruitments/index.html.erb
<%= stylesheet_link_tag "/assets/recruitments.css" %>
<h1>募集一覧</h1>
<div class="fixed-top">
    <div class="float-right">
    <%= link_to "ログアウト", logout_path, method: :delete, class: "btn btn-danger" %>
    </div>
</div>
<%= link_to "Apexフレンドを募集する！", new_recruitment_path, class: "btn btn-primary" %>
<div class="search">

<h3 >募集検索</h3>
<%= form_with url: recruitments_search_path, method: :get, local: true do |f| %>
    <%= f.label :mode, 'モード' %>
    <%= f.select :mode,  [["ランクマッチ","ランクマッチ"],["カジュアル","カジュアル"],["イベント","イベント"],["指定無し","指定無し"]] %>
    <%= f.label :want_chara, '使いたいキャラ' %>
    <%= f.select :want_chara,  [["レイス","レイス"], ["パスファインダー","パスファインダー"], ["オクタン", "オクタン"], ["ミラージュ", "ミラージュ"], 
    ["バンガロール","バンガロール"], ["ジブラルタル", "ジブラルタル"], ["ローバ", "ローバ"], ["レブナント", "レブナント"], ["ライフライン", "ライフライン"],
    ["コースティック", "コースティック"], ["ホライゾン", "ホライゾン"],["ブラッドハウンド", "ブラッドハウンド"], ["クリプト", "クリプト"], 
    ["ランパート", "ランパート"], ["ワットソン", "ワットソン"],["誰でも","誰でも"]] %><br>
    
    <%= f.submit '検索', class: "btn btn-info" %>
    
<% end %>
</div>    
<table class="table table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col">投稿ユーザー</th>
      <th scope="col">DiscordID</th>
      <th scope="col">モード</th>
      <th scope="col">要求ランク</th>
      <th scope="col">Use Legend</th>
      <th scope="col">Want Legend</th>
      <th scope="col">Play Style</th>
      <th scope="col">募集状況</th>
      <th scope="col">※募集者のみ表示</th>
    </tr>
  </thead>
 </table>
<% @recruitments.each do |recruitment| %>
  <table class="table table-bordered">
  <tbody>
    <tr>
      <th scope="row"><%= link_to "#{User.find_by(id: recruitment.user_id).name}", "/users/#{recruitment.user_id}", method: :get %></th>
      <td><%= "#{User.find_by(id: recruitment.user_id).discord_id}" %></td>
      <td><%= recruitment.mode %></td>
      <td><%= recruitment.rank %></td>
      <td><%= recruitment.use_chara %></td>
      <td><%= recruitment.need_chara %></td>
      <td><%= recruitment.play_style %></td>
      <td><% if recruitment.flag == 0 %>
            <%= link_to "募集中","/recruitments/#{recruitment.id}" %>
          <% else %>
            <%= link_to "募集終了","/recruitments/#{recruitment.id}" ,:style=>"color:red;"%>
          <% end %>
          
          <% if recruitment.user_id == session[:user_id] && recruitment.flag ==0 %>
              <%= form_with model: recruitment do |f| %>
                   <p><%= f.check_box :flag %><%= f.label :flag, "募集を締め切る" %>
                   </p>
                   <%= f.submit "更新"  %>
               <% end %>
          <% else %>
          <% end %>
      </td>
      <td>
      <% if recruitment.user_id == session[:user_id]  %> 
      <%= link_to '削除', "/recruitments/#{recruitment.id}", method: :delete %>
      <% else %>
      <% end %> 


        <% if recruitment.user_id == session[:user_id] %>
          <%= link_to image_tag('/assets/twitter.png', :class => "add_style"), "https://twitter.com/share?url=#{ request.url }/#{recruitment.id}", title: 'タイトル', target: '_blank', class: 'add_style' %>
        <% end %>
      </td>  
    </tr>
   
  </tbody>
  </table>
<% end %>
<%= link_to_prev_page @recruitments, '前のページ', class: "d-flex align-items-end" %>
<%= link_to_next_page @recruitments, '次のページ', class: "next" %>

app/views/recruitments/new.html.erb
<%= stylesheet_link_tag "/assets/recruitments.css" %>

<div>
  <div class="col-md-4 offset-md-4">
  <h2 class="text-center pt-5">Apex Friendsを探そう！</h2>
  
  <div class="form-group">
  <%= form_with model: @recruitment, class: :form, local: true do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <%= f.label :mode, 'モード' %>
  <%= f.select :mode,  [["ランクマッチ","ランクマッチ"],["カジュアル","カジュアル"],["イベント","イベント"],["指定無し","指定無し"]] %><br>
  <%= f.label :rank, '希望ランク' %>
  <%= f.text_field :rank %><br>
  <%= f.label :use_chara, '使うキャラ' %>
  <%= f.select :use_chara,  [["レイス","レイス"], ["パスファインダー","パスファインダー"], ["オクタン", "オクタン"], ["ミラージュ", "ミラージュ"], 
    ["バンガロール","バンガロール"], ["ジブラルタル", "ジブラルタル"], ["ローバ", "ローバ"], ["レブナント", "レブナント"], ["ライフライン", "ライフライン"],
    ["コースティック", "コースティック"], ["ホライゾン", "ホライゾン"],["ブラッドハウンド", "ブラッドハウンド"], ["クリプト", "クリプト"], 
    ["ランパート", "ランパート"], ["ワットソン", "ワットソン"],["誰でも","誰でも"]], class: "form-control" %><br>
  <%= f.label :need_chara, '使って欲しいキャラ' %>
  <%= f.select :need_chara,  [["レイス","レイス"], ["パスファインダー","パスファインダー"], ["オクタン", "オクタン"], ["ミラージュ", "ミラージュ"], 
    ["バンガロール","バンガロール"], ["ジブラルタル", "ジブラルタル"], ["ローバ", "ローバ"], ["レブナント", "レブナント"], ["ライフライン", "ライフライン"],
    ["コースティック", "コースティック"], ["ホライゾン", "ホライゾン"],["ブラッドハウンド", "ブラッドハウンド"], ["クリプト", "クリプト"], 
    ["ランパート", "ランパート"], ["ワットソン", "ワットソン"],["誰でも","誰でも"]] %><br>
    <%= f.label :play_style, 'プレイスタイル' %>
    <%= f.text_field :play_style %><br>
    <%= f.submit '登録する', {class: "btn btn-primary"} %>
  <% end %>
  </div>
   
    <%= link_to "トップに戻る", recruitments_path ,{class: "btn btn-outline-secondary"}%>
  
  </div>
</div>

app/views/recruitments/search.html.erb
<%= stylesheet_link_tag "/assets/recruitments.css" %>
<h1>検索結果</h1>
<table class="table table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col">投稿ユーザー</th>
      <th scope="col">DiscordID</th>
      <th scope="col">モード</th>
      <th scope="col">要求ランク</th>
      <th scope="col">Use Legend</th>
      <th scope="col">Want Legend</th>
      <th scope="col">Play Style</th>
      <th scope="col">募集状況</th>
      <th scope="col"></th>
    </tr>
  </thead>
 </table>
<% @recruitments.each do |recruitment| %>
<table class="table table-bordered">
  <tbody>
    <tr>
      <th scope="row"><%= link_to "#{User.find_by(id: recruitment.user_id).name}", "/users/#{recruitment.user_id}", method: :get %></th>
      <td><%= "#{User.find_by(id: recruitment.user_id).discord_id}" %></td>
      <td><%= recruitment.mode %></td>
      <td><%= recruitment.rank %></td>
      <td><%= recruitment.use_chara %></td>
      <td><%= recruitment.need_chara %></td>
      <td><%= recruitment.play_style %></td>
      <td><% if recruitment.flag == 0 %>
            <%= link_to "募集中","/recruitments/#{recruitment.id}" %>
          <% else %>
            <%= link_to "募集終了","/recruitments/#{recruitment.id}" ,:style=>"color:red;"%>
          <% end %>
      </td>
    </tr>
   
  </tbody>
  </table>
<% end %>

<%= link_to "トップに戻る", recruitments_path, {class: "btn btn-outline-secondary"} %>

app/views/recruitments/show.html.erb
<%= stylesheet_link_tag "/assets/recruitments.css" %>
<h1>募集詳細</h1>

<p class="lead">モード：<%= @recruitment.mode %></p>
<p class="lead">要求ランク：<%= @recruitment.rank %></p>
<p class="lead">Use Legend：<%= @recruitment.use_chara %></p>
<p class="lead">Want Legend：<%= @recruitment.need_chara %></p>
<p class="lead">Play Style：<%= @recruitment.play_style %></p>
<p class="lead">募集状況：<%= @recruitment.flag==0? "募集中" : "募集終了" %></p>
    <% if @recruitment.user_id == session[:user_id] && @recruitment.flag ==0  %> 
        <%= form_with model: @recruitment do |f| %>
            <p>
            <%= f.check_box :flag %>
            <%= f.label :flag, "チェックして更新で募集終了" %>
            
            <%= f.submit "更新"  %>
            </p>
            <p>
            Twiiterで呼びかける
            <%= link_to image_tag('/assets/twitter.png', :class => "add_style"), "https://twitter.com/share?url=Apex一緒にやる人募集中！", title: 'Twiiterで呼びかける', target: '_blank', class: 'add_style' %>
            </p>
        <% end %>
    <% else %>
    <% end %>

<%= link_to "トップに戻る", recruitments_path,  {class: "btn btn-outline-secondary"} %>

app/views/top/main.html.erb
<%= stylesheet_link_tag "/assets/top.css" %>
<%= stylesheet_link_tag "/assets/recruitments.css" %>
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-12 cover-img" style="background-image:url('/assets/ape3-be7397da8072d30447561ad8616f27a99a1a543234510176444c2e3023235dae.png');">
			<div class="cover-text text-center">
			  
				<h3>このサービスについて</h3>
				<p>『Apex Legends』を人としたいと思う事はありませんか？</p>
				<p>そんな時、どういうキャラを使うのか、どんなプレイスタイルなのかで悩むことがありますよね。</p>
				<p>このサービスはその悩みを解決します。</p>
			</div>
		</div>
	</div>
</div>




<div class="fixed-top">
    <div class="float-right">
　　<%= link_to "新規登録", "users/new" ,{class: "btn btn-primary pull-left btn-lg"}%>
    <%= link_to "ログイン", login_url ,{class: "btn btn-info pull-right btn-lg"}%>
    </div>
</div>

<h1>募集一覧</h1>
<table class="table table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col">投稿ユーザー</th>
      <th scope="col">DiscordID</th>
      <th scope="col">モード</th>
      <th scope="col">要求ランク</th>
      <th scope="col">Use Legend</th>
      <th scope="col">Want Legend</th>
      <th scope="col">Play Style</th>
      <th scope="col">募集状況</th>
    </tr>
  </thead>
 </table>
<% @recruitments.each do |recruitment| %>


<table class="table table-bordered">
  <tbody>
    <tr>
      <th scope="row"><%= "#{User.find_by(id: recruitment.user_id).name}" %></th>
      <td><%= "#{User.find_by(id: recruitment.user_id).discord_id}" %></td>
      <td><%= recruitment.mode %></td>
      <td><%= recruitment.rank %></td>
      <td><%= recruitment.use_chara %></td>
      <td><%= recruitment.need_chara %></td>
      <td><%= recruitment.play_style %></td>
      <td>
          <% if recruitment.flag == 0 %>
            <%=  "募集中" %>
          <% else %>
           <span>
             <%= "募集終了"%>
           </span>
            
          <% end %>
      </td>
    </tr>
   
  </tbody>
</table>
<% end %>

app/views/users/new.html.erb
 <%= stylesheet_link_tag "/assets/users.css" %>

<h1>ユーザー登録</h1>

<% if @user.errors.any? %>
  <div class="alert alert-warning">
    <ul>
        <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @user, class: :form, local: true do |f| %>
    <%= f.label :name, 'ユーザー名' %>
    <%= f.text_field :name %><br>
    <%= f.label :discord_id, 'DiscordID' %>
    <%= f.text_field :discord_id %><br>
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password %><br>
    <%= f.label :password_confirmation, 'パスワード(確認)' %>
    <%= f.password_field :password_confirmation %><br>
    <%= f.submit '登録する' %>
<% end %>
<%= link_to "トップに戻る", root_url, {class: "btn btn-outline-secondary"} %>

app/views/users/show.html.erb
<h1>プロフィール</h1>

<%= "ユーザ名：" + @user.name %>
<p>今までの募集</p>
<%= "最も良くプレイするモード： #{@most_mode}" %>
<%= "最も良く使うキャラ： #{@most_chara}" %>

<p><% if @user.id == session[:user_id] %> 
    <%= link_to "ユーザーの削除", "/users/#{session[:user_id]}", method: :delete, data: { confirm: "アカウント情報を削除しますよろしいですか？" }, class: "btn btn-danger" %>
<% else %></p>
<% end %>
<p><div class="aa">  
    <%= link_to "トップに戻る", recruitments_path, {class: "btn btn-outline-secondary"} %>
</div></p>

<table class="table table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col">投稿ユーザー</th>
      <th scope="col">モード</th>
      <th scope="col">要求ランク</th>
      <th scope="col">Use Legend</th>
      <th scope="col">Want Legend</th>
      <th scope="col">Play Style</th>
      <th scope="col">募集状況</th>
    </tr>
  </thead>
 </table>
<% @recruitments.each do |recruitment| %>


<table class="table table-bordered">
  <tbody>
    <tr>
      <th scope="row"><%= link_to "#{User.find_by(id: recruitment.user_id).name}", "/users/#{recruitment.user_id}", method: :get %></th>
      <td><%= "#{User.find_by(id: recruitment.user_id).discord_id}" %></td>
      <td><%= recruitment.mode %></td>
      <td><%= recruitment.rank %></td>
      <td><%= recruitment.use_chara %></td>
      <td><%= recruitment.need_chara %></td>
      <td><%= recruitment.play_style %></td>
      <td><% if recruitment.flag == 0 %>
            <%= link_to "募集中","/recruitments/#{recruitment.id}" %>
          <% else %>
            <%= link_to "募集終了","/recruitments/#{recruitment.id}" ,:style=>"color:red;"%>
          <% end %>
      </td>
     
    </tr>
   
  </tbody>
  </table>
<% end %>